server:
  port: 1112

spring:
  application:
    name: producer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tzc.ljq.cloudapi.model
